configuration:
  backupStorageLocation:
  - bucket: sock-shop-velero-backups
    provider: aws
  volumeSnapshotLocation:
  - config:
      region: eu-west-3
    provider: aws
initContainers:
- name: velero-plugin-for-aws
  image: velero/velero-plugin-for-aws:latest
  volumeMounts:
  - mountPath: /target
    name: plugins
credentials:
  useSecret: false
serviceAccount:
  server:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::700778905650:role/eks-velero-backup"