apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    alb.kubernetes.io/component: controller
    alb.kubernetes.io/name: aws-load-balancer-controller
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::518551558056:role/aws-load-balancer-controller